platform :ios, '9.0'
target '百思不得姐(KDL)' do
pod 'AFNetworking', '~> 3.0'
pod 'SVProgressHUD'
pod 'MJExtension'
pod 'SDWebImage', '~>3.7'
pod 'MJRefresh'
pod 'DACircularProgress', '~> 2.3.1'
pod "pop"
end